name: ${project.artifactId}
main: ${project.groupId}.UHC
version: 2020.1.27.1-RC-A

commands:
  uhc:
  whitelist:
    aliases: [wl]
    usage: "\u00A7cCorrect usage: /whitelist <add:remove:clear:all:on:off> [Player]"
  team:
    aliases: [teams, squad]
    usage: "\u00A7cCorrect usage: /team <create:invite:accept:deny:kick:leader:disband:chat> [Player:Message]"
  config:
    aliases: [cfg, uhc]
    usage: "\u00A7cCorrect usage: /config <value> <data>"