name: ${project.artifactId}
main: ${project.groupId}.UHC
version: 2020.1.27.1-RC-A

commands:
  uhc:
  whitelist:
    aliases: [wl]
    usage: "\u00A7cCorrect usage: /whitelist <add:remove:clear:all:on:off> [Player]"
  team:
    aliases: [teams, squad]
    usage: "\u00A7cCorrect usage: /team <create:invite:accept:deny:kick:leader:disband:chat> [Player:Message]"
  config:
    aliases: [cfg, uhc]
    usage: "\u00A7cCorrect usage: /config <value> <data>"
  practice:
    aliases: [arena, a, p]
    usage: "\u00A7cCorrect usage: /practice <value> <data>"
  msg:
    aliases: [tell, private, r, reply]
  fix:
  kt:
  heal:
  feed:
  respawn:
  dq:
  findoff:
  helpop:
  invsee:
  latescatter:
softdepend: [HolographicDisplays]